# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none
# - main

resources:
- repo: self

stages:
- stage: Build_our_container
  jobs:
  - job:
    displayName: "Build our container"
    container:
      image: vernovaacr.azurecr.io/testimage:1123
      endpoint: 'vernovaacr'
    steps:
    - script: terraform --version
      displayName: 'Check terraform version'

